### ISSUE TITLE
QPS and concurrency behavior feels unintuitive

### ISSUE THREAD

**Issue by akerekes** [rakyll/hey#72] opened 2017-11-09 01:37 UTC
When I run `hey -n <request_count> -c 10 -q 10 <url>` I'd expect either of the following 2 behavior:

  * my service gets about 10 requests per second (not necessarily but presumably mostly uniformly distributed among the concurrent connections) or
  * my service gets about 100 requests per second (i.e. 10 req/s multiplied by concurrency)

Instead what I observe is that requests from a worker are issued slower than QPS if the requests take longer than 1/QPS seconds. E.g. if a request takes 200ms, and QPS is set to 10, the worker will only issue 5 requests per second.

This makes the load testing difficult to parametrize if I want to test whether my service can serve a certain QPS value.

Thinking more about this, I think it's best to set QPS to 1 and ramp up concurrency to the level I want my server to observe as overall QPS.
Only problem is if the requests take longer than 1 second. In this case it would be still trial and error to determine what concurrency to set to achieve a certain QPS.

**Comment by mdakin** [comment] 2017-12-19 16:52
I agree that current rate limit behavior is incorrect. I think in previous versions rate limit was global but looks like it is per worker now. which makes it pretty much useless. I will have a look when I have time.

**Comment by mdakin** [comment] 2017-12-21 12:25
@akerekes Actually reading your comment and looking at the code again (I wrote the initial rate limiting code long time ago) , I think it makes sense to make it per worker. This number is the **upper limit** of the number of requests sent by the worker.  It is natural that lower limit is unknown and worker send new requests only after previous one is finished. 
I now think making a global rate limit is also trickier and I think not worth the complexity it brings. I am closing this issue as "working as intended".

**Closed by mdakin** 2017-12-21 12:25 UTC

**Comment by akerekes** [comment] 2017-12-27 21:48
@mdakin I agree that it may be difficult to implement the behavior I hoped to see. Maybe better documentation and/or examples to show the expected behavior for different QPS settings would be sufficient.
